pipeline {
    agent none
   
    stages {
         
        stage('Build') {
              agent {
        docker {
          image 'maven:3-alpine'
           args '-v /root/.m2:/root/.m2'
       }
    }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage ('Build ansible') {
            agent any
             environment {
        ANSIBLE_VAULT= credentials('vault-ansible')
           
    }
           
            steps {
                       script {
                           def subject= "Job: '$env.JOB_NAME [env.BUILD_NUMBER]'"
                           def summary= "$subjetc: {env.BUILD_NUMBER}"
                           def details = """<p>STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
    <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>"""    
            
                sh 'pwd'
                sh 'ansible-playbook ansible/beanstalk-playbook.yml --vault-password-file $ANSIBLE_VAULT'
                emailext (
                    subject: subject,
                    body: details,
                    to: 'boukhrisghassen@gmail.com'
                    
                    )
                       }
            }
        }
        stage('Test') {
             agent {
        docker {
          image 'maven:3-alpine'
           args '-v /root/.m2:/root/.m2'
       }
    }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
