pipeline {
    agent none
    environment {
        ansible-vault= credentials('vault-ansible')
    }
    stages {
         
        stage('Build') {
              agent {
        docker {
          image 'maven:3-alpine'
           args '-v /root/.m2:/root/.m2'
       }
    }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage ('Build ansible') {
            agent any
            steps {
                sh 'pwd'
                sh 'ansible-playbook ansible/beanstalk-playbook.yml --vault-password-file $ansible-vault'
            }
        }
        stage('Test') {
             agent {
        docker {
          image 'maven:3-alpine'
           args '-v /root/.m2:/root/.m2'
       }
    }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
